// Run this first
task jfrogAssembleApptentiveKit(type: GradleBuild) {
    buildName = "jfrogAssembleApptentiveKit"
    tasks = ['apptentive-kit-android:assembleRelease']
}

// Run this after jfrogAssembleApptentiveKit
task jfrogPublishApptentiveKit(type: GradleBuild) {
    buildName = "jfrogPublishApptentiveKit"
    startParameter.projectProperties = project.gradle.startParameter.projectProperties
    tasks = ['apptentive-kit-android:artifactoryPublish']
    dependsOn jfrogAssembleApptentiveKit
}
