name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest -x apptentive-kit-android:test

  assemble:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug
        
      - name: Rename Artifact
        run: mv app/build/outputs/apk/dev/debug/app-dev-debug.apk "app/build/outputs/apk/dev/debug/app-dev-debug-${{ github.sha }}.apk"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "Debug APK ${{ github.sha }}"
          path: "app/build/outputs/apk/dev/debug/app-dev-debug-${{ github.sha }}.apk"

